#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/10-logchimp
PROCESS_NAME="logchimp-frontend"

check_container_initialized
check_service_initialized init 10-logchimp

liftoff

export VUE_APP_SEVER_URL="${BACKEND_PROTOCOL}://${BACKEND_HOSTNAME}:${BACKEND_PORT}"

print_info "Starting Logchimp Frontend"
cd /app
yarn run frontend:dev
