#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="logchimp"

sanity_db postgres
db_ready postgres
sanity_var APP_KEY "Secret Key for encryption/decryption"

generate_configuration
configure_backend

liftoff