#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="logchimp-backend"

check_container_initialized
check_service_initialized init

liftoff

print_info "Starting Logchimp backend"
cd /app
yarn run server:dev
